### ISSUE TITLE
Social media links

### ISSUE THREAD

**Issue by patpluspun** [NextGen-Coop/ngc.github.io#1]
We need to setup social media presences and get them linked to in the footer. I would suggest:
* ~~Github~~
* Facebook
* Twitter

At a minimum. We can decide on more as the need grows.

Once the accounts are made, we set up links in https://github.com/NextGen-Coop/ngc-website/blob/a1ac3fa191254b092941cf434878ff3db23688ea/_includes/social.html#L1 and names in https://github.com/NextGen-Coop/ngc-website/blob/a1ac3fa191254b092941cf434878ff3db23688ea/_config.yml#L22

**Comment by aditya28sarin** [comment]
Can you assign me this issue?

**Comment by patpluspun** [comment]
Hi @aditya28sarin

While I appreciate your offer, this repo is intended for members of our cooperative to build and learn things for our public website.  We're still in the startup phase, so I'm unsure if we are legally able to pursue offshore team members.  I will check the possibility though, and if so you are welcome to join our cooperative.
